addons:
  apt:
    packages:
    - nsis
language: python
python:
- '3.6'
install: pip install pynsist
script: pynsist installer.cfg
deploy:
  provider: releases
  api_key:
    secure: qdLqD2tYeOwdWab3RW2H8nk0oJOky1UAzIKGKq4IYE69LxlIAp8k3Ar7em+6XS0tO6rKvEtRAsrLaIGVrAac6TrTojp6tOff9x047cZTetWYwUOnndO3wJCWvkSvixnGoNBwB1u8a56XfAYDEHkipZfIbfFgCSZTCvujjFhxo5PLXj1gA28dNdDmbhfxNWkidTnQzH/F4DFvwcWvmvyMZVnsYQtujXKtog0RVgVaXMwiydaa3IUBK2+pCY/4Ef3GKPbEUTy9jqRjYNEKrGvReckCLlOme6EOIt+VyuGFEF3h53DzeHFlJ/N6sXdbZ8NR3lxQ57TFQFIzBqKHIOWfqTpFBjiXqOsFCcPijOKS9POL6Kt14BLmbkkCBohF+EYml0BMQOP3ClwHtJzvS2K9QwqsN6/sBAy5nzqM4dbbwKexrPbZP9BET7bkQ9I5H4WzjF7nzjbKQ3GKrYQ42CUEa0v5/PVeyRG87fp4m6TYeSWP8Tr3yq8E3rji1uPhfku0RHXABpNzdKrrZfsCCsaqMg/CS5gfjalj/vC0/cIx6CttF1JtXGL5gKILss7R7GJFf0EPgXFOoPvSuQ2iGp2Zj4LrIsdT55Tjx5BslRE/6H+mTfAGQ3TDnQNpZXVMXAgWl6SFJ1GkiKXzTMM7Ssc/jipUoSJi2BmHAMoTt5Q9YuM=
  file: build/nsis/VismaPetraImport_1.1.exe
  on:
    repo: jswetzen/sie-parse
  skip_cleanup: true
